{
  "name": "json-ci",
  "on": {
    push: {},
    "schedule": [
      { "cron": "0 0 * * 0" }
    ]
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "run": "echo '${{ github.actor }} will never forgive these sins!'"
        },
        {
          "name": "Update README",
          "run": "echo 'Another act of heresy committed on $(date -u)' >> README.md"
        },
        {
          "name": "Set up auth",
          "run": "git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com'"
        },
        {
          "name": "Commit changes",
          "run": "git add README.md && git commit -m 'Documented another sin' || echo 'Nothing to commit'"
        },
        {
          "name": "Push changes",
          "env": {
            "TOKEN": "${{ secrets.GITHUB_TOKEN }}"
          },
          "run": "git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main"
        }
      ]
    }
  }
}
