{
  "name": "json-ci",
  "on": {
    push: {},
    "schedule": [
      { "cron": "0 0 * * 0" }
    ]
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v4" },
        {
          "run": "echo '${{ github.actor }} will never forgive these sins!'"
        },
        {
          "name": "Update README",
          "run": "echo 'Another act of heresy committed on $(date -u)' >> README.md"
        },
        {
          "name": "Commit changes",
          "run": "git config user.name 'github-actions' && git config user.email 'github-actions@github.com' && git add README.md && git commit -m 'Documented another sin' || echo 'No changes to commit'"
        },
        {
          "name": "Push changes",
          "run": "git push"
        }
      ]
    }
  }
}
